.PHONY: all clean build package

all: clean build package

build:
	# Build all Rust binaries in release mode
	cargo build 

package:
	# Create release directory structure
	mkdir -p target/debug/config
	mkdir -p target/debug/deps/config

	# Copy additional required files
	cp -r config/* target/debug/config/
	cp config_real.toml target/debug/config/config.toml
	cp config_real.toml target/debug/deps/config/config.toml

	# cp -r repl/bin/* midas-release/bin/engine-bin
	
